apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
spec:
  clusterIP: None  # Headless service
  selector:
    app: redis
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
